<?php

declare(strict_types=1);

namespace DDD\Domain\AI\Repo\Argus\Traits;

use DDD\Domain\AI\Entities\Models\AIModel;
use DDD\Domain\AI\Entities\Prompts\AIPrompt;
use DDD\Domain\AI\Exceptions\AiBudgetExceededException;
use DDD\Domain\AI\Repo\Argus\Attributes\ArgusLanguageModel;
use DDD\Domain\Base\Repo\Argus\Traits\ArgusTrait;
use DDD\Domain\Base\Repo\Argus\Utils\ArgusApiOperation;
use DDD\Domain\Common\Entities\Accounts\Account;
use DDD\Domain\Common\Entities\MediaItems\GenericMediaItem;
use DDD\Domain\Common\Entities\MediaItems\MediaItem;
use DDD\Domain\Common\Entities\MediaItems\Photo;
use DDD\Domain\Common\Entities\Money\MoneyAmount;
use DDD\Infrastructure\Exceptions\BadRequestException;
use DDD\Infrastructure\Exceptions\InternalErrorException;
use DDD\Infrastructure\Exceptions\NotFoundException;
use DDD\Infrastructure\Traits\ReflectorTrait;
use Doctrine\DBAL\Exception;
use JsonException;
use Psr\Cache\InvalidArgumentException;
use ReflectionException;

trait ArgusAILanguageModelTrait
{
    use ReflectorTrait, ArgusTrait;

    /** @var ArgusLanguageModel|null */
    protected ?ArgusLanguageModel $argusLanguageModel = null;

    /** @var AIModel|null */
    protected ?AIModel $aiModel = null;

    /** @var AIPrompt|null */
    protected ?AIPrompt $aiPrompt = null;

    /** @var AIPrompt|null */
    protected ?AIPrompt $aiSystemPrompt = null;

    /** @var string|null The text generated by the AI */
    protected ?string $aiGeneratedResponse;

    /** @var int The amount of tokens used for the AI service */
    protected int $consumedTokens = 0;

    /** @var MoneyAmount|null The costs for AI Service usage */
    protected ?MoneyAmount $aiCosts = null;

    /** @var float The temperature is a parameter that controls the randomness of the LLM's output. A higher temperature will result in more creative and imaginative text, while a lower temperature will result in more accurate and factual text */
    protected float $temperature = 0.8;

    /** @var AIPrompt Temporary stored AIPromptWithParametersApplied */
    protected AIPrompt $aiPromptWithParametersApplied;

    /** @var string|array Temporary stored userContent */
    protected string|array $userContent;

    /**
     * Getter for the $aiGeneratedResponse property
     * @return string|null
     */
    public function getAiGeneratedResponse(): ?string
    {
        return $this->aiGeneratedResponse ?? null;
    }

    /**
     * Setter for the $aiGeneratedResponse property
     * @param string|null $aiGeneratedResponse
     * @return void
     */
    public function setAiGeneratedResponse(?string $aiGeneratedResponse): void
    {
        $this->aiGeneratedResponse = $aiGeneratedResponse;
    }

    /**
     * @return ArgusLanguageModel|null
     * @throws ReflectionException
     */
    public function getArgusLanguageModelInstance(): ?ArgusLanguageModel
    {
        if ($this->argusLanguageModel ?? null) {
            return $this->argusLanguageModel;
        }
        $this->argusLanguageModel = static::getReflectionClass()->getAttributeInstance(ArgusLanguageModel::class);
        return $this->argusLanguageModel;
    }

    /**
     * @return float
     * @throws ReflectionException
     */
    public function getTemperature(): float
    {
        $argusLanguageModelInstance = $this->getArgusLanguageModelInstance();
        if ($argusLanguageModelInstance && isset($argusLanguageModelInstance->temperature)) {
            return $argusLanguageModelInstance->temperature;
        }
        return $this->temperature;
    }

    /**
     * @return AIPrompt|null
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws ReflectionException
     */
    public function getSystemPrompt(): ?AIPrompt
    {
        if (isset($this->aiSystemPrompt)) {
            return $this->aiSystemPrompt;
        }

        $argusLanguageModelInstance = $this->getArgusLanguageModelInstance();
        if (!$argusLanguageModelInstance) {
            return null;
        }

        $systemPromptName = $argusLanguageModelInstance->systemPromptName;
        $systemPromptVersion = $argusLanguageModelInstance->systemPromptVersion;

        if (!$systemPromptName) {
            return null;
        }

        $aiPromptService = AIPrompt::getService();
        $aiPromptService->throwErrors = true;
        $this->aiSystemPrompt = $aiPromptService->getAIPromptByName($systemPromptName);

        return $this->aiSystemPrompt;
    }

    /**
     * Returns AIModel to use, this function can be individualized in Subclasses, e.g. in order to use different models
     * based on need, e.g. on longer input utilize GPT3.5 16K else GPT3.5
     * @return AIModel|null
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws NotFoundException
     * @throws ReflectionException
     */
    public function getAIModel(): ?AIModel
    {
        if (isset($this->aiModel)) {
            return $this->aiModel;
        }
        if (isset($this->getArgusLanguageModelInstance()->defaultAIModelName)) {
            $aiModelService = AIModel::getService();
            $aiModelService->throwErrors = true;
            $this->aiModel = $aiModelService->getAIModelByName(
                $this->getArgusLanguageModelInstance()->defaultAIModelName
            );
        }
        return $this->aiModel;
    }

    /**
     * Returns AIPrompt to use, this function can be individualized in Subclasses, e.g. in order to use different prompts
     * based on need
     * @return AIPrompt|null
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws ReflectionException
     */
    public function getAIPrompt(): ?AIPrompt
    {
        if (isset($this->aiPrompt)) {
            return $this->aiPrompt;
        }
        if (isset($this->getArgusLanguageModelInstance()->defaultAIPromptName)) {
            $aiPromptService = AIPrompt::getService();
            $aiPromptService->throwErrors = true;
            $argusLanguageModel = $this->getArgusLanguageModelInstance();
            $this->aiPrompt = $aiPromptService->getAIPromptByName(
                $argusLanguageModel->defaultAIPromptName,
            );
        }
        return $this->aiPrompt;
    }

    /**
     * @param AIPrompt $aiPrompt
     * @return void
     */
    public function setAIPrompt(AIPrompt $aiPrompt): void
    {
        $this->aiPrompt = $aiPrompt;
    }

    /**
     * @return string|array
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws NotFoundException
     * @throws ReflectionException
     * @throws JsonException
     */
    public function getUserContentCached(): string|array
    {
        if (!isset($this->userContent)) {
            $this->userContent = $this->getUserContent();
        }
        return $this->userContent;
    }

    /**
     * @return AIPrompt
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws NotFoundException
     * @throws ReflectionException
     */
    public function getAIPromptWithParametersAppliedCached(): AIPrompt
    {
        if (!isset($this->aiPromptWithParametersApplied)) {
            $this->aiPromptWithParametersApplied = $this->getAIPromptWithParametersApplied();
        }
        return $this->aiPromptWithParametersApplied;
    }

    /**
     * @return bool
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws JsonException
     * @throws NotFoundException
     * @throws ReflectionException
     */
    public function isAIBudgetSufficientForOperation(): bool
    {
        // in some admin operations, Account is set in getUserContent function or getAIPromptWithParametersApplied
        $this->getUserContentCached();
        $this->getAIPromptWithParametersAppliedCached();
        return true;
    }

    /**
     * @return string|array Returns user content for AIModel
     */
    abstract public function getUserContent(): string|array;

    /**
     * @return AIPrompt Return AIPrompt with applied parameters
     */
    abstract public function getAIPromptWithParametersApplied(): AIPrompt;

    /**
     * @return array[]|null
     * @throws AiBudgetExceededException
     * @throws BadRequestException
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws JsonException
     * @throws NotFoundException
     * @throws ReflectionException
     */
    protected function getLoadPayloadInternal(): ?array
    {
        $aiModel = $this->getAIModel();

        if (!$this->isAIBudgetSufficientForOperation()) {
            throw new AiBudgetExceededException('AI Operation exceeds available AI Budget');
        }

        $userContentHasCompleteFormat = false;

        // --- Normalize/prepare user content (incl. images -> data URLs) ---
        if ($this->getUserContentCached() && is_array($this->userContent)) {
            // Detect "complete" Chat messages format (array of {role, content, ...})
            $first = reset($this->userContent);
            if (is_array($first) && isset($first['role'])) {
                $userContentHasCompleteFormat = true;
            }

            foreach ($this->userContent as $i => $element) {
                // Case A: top-level content-part style: ['type' => 'image_url', 'image_url' => ['image' => Photo|GenericMediaItem]]
                if (isset($element['type']) && $element['type'] === 'image_url') {
                    if (!isset($element['image_url']['image']) || !($element['image_url']['image'] instanceof Photo || $element['image_url']['image'] instanceof GenericMediaItem || $element['image_url']['image'] instanceof MediaItem)) {
                        throw new InternalErrorException(
                            "User Content of type 'image_url' must contain key 'image' with an instance of Photo or GenericMediaItem"
                        );
                    }
                    /** @var Photo $photo */
                    $photo = $element['image_url']['image'];
                    if (!(isset($photo->mediaItemContent->fileFormat) && $photo->mediaItemContent->getBase64EncodedContent())) {
                        throw new InternalErrorException(
                            "User Content of type 'image_url' must reference a Photo with mediaItemContent.fileFormat and base64EncodedContent filled"
                        );
                    }
                    $element['image_url']['url'] = "data:image/{$photo->mediaItemContent->fileFormat};base64,{$photo->mediaItemContent->getBase64EncodedContent()}";
                    unset($element['image_url']['image']);
                    $this->userContent[$i] = $element;
                    continue;
                }

                // Case B: message format with content array parts
                if (isset($element['content']) && is_array($element['content'])) {
                    foreach ($element['content'] as $j => $part) {
                        if (isset($part['type']) && $part['type'] === 'image_url') {
                            if (!isset($part['image_url']['image']) || !($part['image_url']['image'] instanceof Photo || $part['image_url']['image'] instanceof GenericMediaItem)) {
                                throw new InternalErrorException(
                                    "Message content of type 'image_url' must contain key 'image' with an instance of Photo or GenericMediaItem"
                                );
                            }
                            /** @var Photo $photo */
                            $photo = $part['image_url']['image'];
                            if (!(isset($photo->mediaItemContent->fileFormat) && $photo->mediaItemContent->getBase64EncodedContent())) {
                                throw new InternalErrorException(
                                    "Message content of type 'image_url' must reference a Photo with mediaItemContent.fileFormat and base64EncodedContent filled"
                                );
                            }
                            $part['image_url']['url'] = "data:image/{$photo->mediaItemContent->fileFormat};base64,{$photo->mediaItemContent->getBase64EncodedContent()}";
                            unset($part['image_url']['image']);
                            $element['content'][$j] = $part;
                        }
                    }
                    $this->userContent[$i] = $element;
                }
            }
        }

        // --- Google Gemini vendor path ---
        if ($aiModel->vendor === AIModel::VENDOR_GOOGLE) {
            // System instruction (optional)
            $systemPrompt = method_exists($this, 'getSystemPrompt') ? $this->getSystemPrompt() : null;
            $systemInstruction = $systemPrompt ? $systemPrompt->getPromtTextWithParametersApplied() : '';

            // Task-specific prompt that we always lead with
            $taskSpecificPrompt = $this->getAIPromptWithParametersAppliedCached()->getPromtTextWithParametersApplied();

            // Build Gemini "parts" with text + inline image data
            $parts = [];
            if (is_string($taskSpecificPrompt) && $taskSpecificPrompt !== '') {
                $parts[] = ['text' => $taskSpecificPrompt];
            }

            $appendImageDataUrlToParts = static function (string $dataUrl, array &$parts): void {
                if (str_starts_with($dataUrl, 'data:image/')) {
                    $afterPrefix = substr($dataUrl, strlen('data:image/'));
                    $semiPos = strpos($afterPrefix, ';');
                    $commaPos = strpos($afterPrefix, ',');
                    $mimeSuffix = $semiPos !== false ? substr($afterPrefix, 0, $semiPos) : '';
                    $base64 = $commaPos !== false ? substr($afterPrefix, $commaPos + 1) : '';
                    if ($mimeSuffix !== '' && $base64 !== '') {
                        $parts[] = [
                            'inline_data' => [
                                'mime_type' => 'image/' . $mimeSuffix,
                                'data' => $base64,
                            ],
                        ];
                    }
                }
            };

            // Accept string content, array of parts, or Chat-style messages
            if (is_string($this->userContent)) {
                $parts[] = ['text' => '<user-data>' . $this->userContent . '</user-data>'];
            } elseif (is_array($this->userContent)) {
                $first = reset($this->userContent);
                // Chat-style messages
                if (is_array($first) && isset($first['role'])) {
                    foreach ($this->userContent as $msg) {
                        $content = $msg['content'] ?? null;
                        if (is_string($content)) {
                            $parts[] = ['text' => $content];
                        } elseif (is_array($content)) {
                            foreach ($content as $part) {
                                if (($part['type'] ?? null) === 'text' && isset($part['text'])) {
                                    $parts[] = ['text' => (string)$part['text']];
                                } elseif (($part['type'] ?? null) === 'image_url' && isset($part['image_url']['url'])) {
                                    $appendImageDataUrlToParts((string)$part['image_url']['url'], $parts);
                                }
                            }
                        }
                    }
                } else {
                    // Parts-style array
                    foreach ($this->userContent as $element) {
                        if (($element['type'] ?? null) === 'text' && isset($element['text'])) {
                            $parts[] = ['text' => (string)$element['text']];
                        } elseif (($element['type'] ?? null) === 'image_url' && isset($element['image_url']['url'])) {
                            $appendImageDataUrlToParts((string)$element['image_url']['url'], $parts);
                        }
                    }
                }
            }

            $body = [
                'model' => $aiModel->externalId,
                'contents' => [
                    [
                        'role'  => 'user',
                        'parts' => $parts ?: [['text' => '']],
                    ],
                ],
                'generation_config' => [
                    'temperature'       => $this->getTemperature(),
                    'max_output_tokens' => $aiModel->settings->maxOutputTokens,
                ],
            ];

            if ($systemInstruction !== '') {
                // Keep placement consistent with existing integration expectations
                $body['generation_config']['system_instruction'] = $systemInstruction;
            }

            $argusLanguageModel = method_exists($this, 'getArgusLanguageModelInstance')
                ? $this->getArgusLanguageModelInstance()
                : ($this->argusLanguageModel ?? null);

            if ($argusLanguageModel
                && $argusLanguageModel->responseFormat === ArgusLanguageModel::RESPONSE_FORMAT_JSON_OBJECT
            ) {
                $body['generation_config']['response_mime_type'] = 'application/json';
            }

            return ['body' => $body];
        }

        // --- OpenAI / OpenRouter Chat Completions vendor path (default) ---
        $loadEndpoint = (string)($this->argusSettings->argusLoad->loadEndpoint ?? '');
        $isOpenRouterEndpoint = str_contains(strtolower($loadEndpoint), 'openrouter');

        $modelExternalId = $aiModel->externalId;
        if ($isOpenRouterEndpoint) {
            if (!($aiModel->openRouterExternalId ?? null)) {
                throw new InternalErrorException("No openRouterExternalId configured for model '{$aiModel->name}'");
            }
            $modelExternalId = $aiModel->openRouterExternalId;
        }

        $messages = [];
        if ($userContentHasCompleteFormat && is_array($this->userContent)) {
            // Pass through user-provided messages as-is
            $messages = $this->userContent;
        } else {
            // Build minimal system+user messages
            $messages = [
                [
                    'role'    => 'system',
                    'content' => $this->getAIPromptWithParametersAppliedCached()->getPromtTextWithParametersApplied(),
                ],
                ['role' => 'user', 'content' => $this->userContent],
            ];
        }

        $return = [
            'body' => [
                'model'       => $modelExternalId,
                'messages'    => $messages,
            ],
        ];

        // --- Token limit param differs by model family ---
        if ($aiModel->isReasoningModel) {
            $return['body']['max_completion_tokens'] = (int)$aiModel->settings->maxOutputTokens;
        } else {
            $return['body']['max_tokens'] = (int)$aiModel->settings->maxOutputTokens;
            $return['body']['temperature'] = $this->getTemperature();
        }

        $argusLanguageModel = method_exists($this, 'getArgusLanguageModelInstance')
            ? $this->getArgusLanguageModelInstance()
            : ($this->argusLanguageModel ?? null);

        if ($argusLanguageModel && $argusLanguageModel->responseFormat !== ArgusLanguageModel::RESPONSE_FORMAT_DEFAULT) {
            if ($argusLanguageModel->responseFormat === ArgusLanguageModel::RESPONSE_FORMAT_JSON_OBJECT) {
                $return['body']['response_format'] = ['type' => 'json_object'];
            }
        }

        return $return;
    }

    /**
     * @param mixed|null $callResponseData
     * @param ArgusApiOperation|null $apiOperation
     * @return void
     * @throws BadRequestException
     * @throws Exception
     * @throws InternalErrorException
     * @throws InvalidArgumentException
     * @throws NotFoundException
     * @throws ReflectionException
     */
    public function handleLoadResponseInternal(
        mixed &$callResponseData = null,
        ?ArgusApiOperation &$apiOperation = null
    ): void
    {
        $responseObject = null;
        if (isset($callResponseData->status) && ($callResponseData->status == 200 || $callResponseData->status == 'OK') && ($callResponseData->data ?? null)) {
            $responseObject = $callResponseData->data;
        }
        if (!$responseObject) {
            $this->postProcessLoadResponse($callResponseData, false);
            return;
        }

        // Prefer OpenAI-like structure if present (works for your current Gemini gateway response)
        $loadResult = $responseObject->choices[0]->message->content ?? null;

        // Fallback to Gemini-native structure if choices/message not available
        if ($loadResult === null && isset($responseObject->candidates[0])) {
            $candidate = $responseObject->candidates[0];
            if (isset($candidate->content->parts) && is_array($candidate->content->parts)) {
                $texts = [];
                foreach ($candidate->content->parts as $part) {
                    if (isset($part->text)) {
                        $texts[] = (string)$part->text;
                    }
                }
                $loadResult = $texts ? implode("\n", $texts) : null;
            }
        }

        if (!$loadResult) {
            $this->postProcessLoadResponse($callResponseData, false);
            return;
        }

        $this->applyLoadResult($loadResult);
        $this->postProcessLoadResponse($callResponseData, true);
    }

    /**
     * @return string Removes any ```JSON / HTML etc. markup
     */
    public function removeProgrammingLanguageMarkup(string $input): string
    {
        // Regular expression to match and optionally remove Markdown code blocks with ```html or other languages
        $pattern = '/```[a-zA-Z]+\n?(.*?)```/s';

        // Replace the matched pattern with just the content inside the code block
        $cleanedText = preg_replace($pattern, '$1', $input);

        // Remove trailing commas before closing brackets in JSON objects and arrays
        $cleanedText = preg_replace('/,\s*([\]}])/', '$1', $cleanedText);

        return $cleanedText;
    }

    abstract protected function applyLoadResult(string $resultText): void;
}
